//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam22
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookStore
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public string avtor { get; set; }
        public int countShop { get; set; }
        public int CountStock { get; set; }
        public string Description { get; set; }
        public string Cover { get; set; }
        public Nullable<int> Cost { get; set; }
    }
}
